[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.4"
ci = "github"
installers = ["shell", "powershell", "homebrew"]
tap = "canack/homebrew-tap"
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
publish-jobs = ["homebrew"]
publish-prereleases = false
pr-run-mode = "plan"
install-path = "CARGO_HOME"
install-updater = false
